# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20161204_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default=None, null=True, upload_to=b'', verbose_name='Main image of the product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='store.ProductCategory', verbose_name='Product categories'),
        ),
    ]
