# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20161205_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupoffer',
            name='product_categories',
        ),
        migrations.RemoveField(
            model_name='groupoffer',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productbundle',
            name='free_product',
        ),
        migrations.RemoveField(
            model_name='productbundle',
            name='paid_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('price_per_serving', 'Price per weight'), ('price_per_unit', 'Price per portion')], default='price_per_weight', max_length=32),
        ),
        migrations.DeleteModel(
            name='GroupOffer',
        ),
        migrations.DeleteModel(
            name='ProductBundle',
        ),
    ]
