# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('paid', 'Paid')], default='pending', max_length=16, verbose_name='Sale status')),
                ('first_name', models.CharField(max_length=128, verbose_name='First name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last name')),
                ('telephone_number', models.CharField(max_length=32, verbose_name='Telephone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('code', models.CharField(max_length=16, verbose_name='Sale unique code')),
                ('creation_datetime', models.DateTimeField(verbose_name='Creation datetime')),
                ('online_payment_code', models.CharField(default=None, max_length=64, null=True, verbose_name='Online payment code')),
                ('payment_datetime', models.DateTimeField(default=None, null=True, verbose_name='Online payment datetime')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Price for this sale not including discount', max_digits=10, verbose_name='Total price for this sale')),
                ('group_offer_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Name of the offer')),
                ('group_offer_discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount amount')),
                ('group_offer_discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], max_length=32, verbose_name='Discount type (percent or absolute)')),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Price for this sale including discount', max_digits=10, verbose_name='Final price for this sale')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128, verbose_name='Name of the product')),
                ('product_price', models.DecimalField(decimal_places=2, help_text='Default price of this product', max_digits=10, verbose_name='Price of this product')),
                ('product_price_type', models.CharField(default='price_per_weight', max_length=32, verbose_name='Product price type')),
                ('amount', models.PositiveIntegerField(help_text='Amount of product selected by customer', verbose_name='Amount of product')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Price for the amount of product selected by user', max_digits=10, verbose_name='Total price for this product selection')),
                ('bundle_offer_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Name of the product')),
                ('bundle_offer_bundle_product_units', models.PositiveIntegerField(default=None, null=True, verbose_name='Number of units in the bundle')),
                ('bundle_offer_paid_product_units', models.PositiveIntegerField(default=None, null=True, verbose_name='Number of units the customer must pay')),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Price for the amount of product selected by user including discount', max_digits=10, verbose_name='Final price for this product selection')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_details', to='sale.Sale', verbose_name='Sale')),
            ],
        ),
    ]
