# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20161206_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'', verbose_name='Main image of the product'),
        ),
    ]
