# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_auto_20161206_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the offer')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description of the offer')),
                ('bundle_product_units', models.PositiveIntegerField(default=3, verbose_name='Number of units in the bundle')),
                ('paid_product_units', models.PositiveIntegerField(default=2, verbose_name='Number of units the use must pay')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bundle_offers', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.Product', verbose_name='Paid product')),
            ],
        ),
        migrations.CreateModel(
            name='GroupOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the offer')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description of the offer')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount amount')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], max_length=32, verbose_name='Discount type (percent or absolute)')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_group_offers', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('product_categories', models.ManyToManyField(blank=True, help_text='Product categories that are contained in this offer', to='store.ProductCategory', verbose_name='ProductCategory')),
                ('products', models.ManyToManyField(blank=True, help_text='Products that are contained in this offer', to='store.Product', verbose_name='Products')),
            ],
        ),
    ]
