# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundleoffer',
            name='paid_product_units',
            field=models.PositiveIntegerField(default=2, verbose_name='Number of units the customer must pay'),
        ),
    ]
